/**
 * Mock Data for Property Search Testing
 * Sample properties for development and testing
 */

import { type Property } from '@/stores/search-store';

export const mockProperties: Property[] = [
  {
    id: 1,
    userId: 'user-1',
    propertyType: 'Appartement',
    listingType: 'Vente',
    title: 'Magnifique appartement Haussmannien',
    description: 'Superbe appartement avec vue sur la Tour Eiffel',
    status: 'active',
    price: '850000',
    currency: 'EUR',
    address: '16 Avenue Kléber',
    city: 'Paris',
    state: 'Île-de-France',
    country: 'France',
    postalCode: '75016',
    latitude: 48.8698,
    longitude: 2.293,
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    amenities: ['Parking', 'Balcon', 'Cave', 'Ascenseur'],
    photos: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    userId: 'user-1',
    propertyType: 'Maison',
    listingType: 'Location',
    title: 'Belle maison moderne avec jardin',
    description: 'Maison récente avec grand jardin arboré',
    status: 'active',
    price: '2500',
    currency: 'EUR',
    address: '45 Rue de la Pompe',
    city: 'Neuilly-sur-Seine',
    state: 'Île-de-France',
    country: 'France',
    postalCode: '92200',
    latitude: 48.8844,
    longitude: 2.2761,
    bedrooms: 4,
    bathrooms: 3,
    area: 180,
    amenities: ['Jardin', 'Garage', 'Piscine', 'Terrasse'],
    photos: [
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    userId: 'user-2',
    propertyType: 'Studio',
    listingType: 'Location',
    title: 'Studio lumineux proche métro',
    description: 'Studio rénové avec cuisine équipée',
    status: 'active',
    price: '950',
    currency: 'EUR',
    address: '23 Rue Saint-Antoine',
    city: 'Paris',
    state: 'Île-de-France',
    country: 'France',
    postalCode: '75004',
    latitude: 48.8554,
    longitude: 2.3645,
    bedrooms: 1,
    bathrooms: 1,
    area: 30,
    amenities: ['Meublé', 'Internet', 'Cuisine équipée'],
    photos: [
      {
        id: 3,
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    userId: 'user-2',
    propertyType: 'Loft',
    listingType: 'Vente',
    title: 'Loft industriel atypique',
    description: 'Ancien atelier transformé en loft moderne',
    status: 'active',
    price: '650000',
    currency: 'EUR',
    address: '78 Rue Oberkampf',
    city: 'Paris',
    state: 'Île-de-France',
    country: 'France',
    postalCode: '75011',
    latitude: 48.8654,
    longitude: 2.3794,
    bedrooms: 2,
    bathrooms: 1,
    area: 95,
    amenities: ['Poutres apparentes', 'Double hauteur', 'Parquet'],
    photos: [
      {
        id: 4,
        url: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    userId: 'user-3',
    propertyType: 'Duplex',
    listingType: 'Vente',
    title: 'Duplex avec terrasse panoramique',
    description: 'Vue imprenable sur tout Paris',
    status: 'active',
    price: '1200000',
    currency: 'EUR',
    address: '12 Avenue Montaigne',
    city: 'Paris',
    state: 'Île-de-France',
    country: 'France',
    postalCode: '75008',
    latitude: 48.866,
    longitude: 2.3047,
    bedrooms: 4,
    bathrooms: 3,
    area: 160,
    amenities: ['Terrasse', 'Parking', 'Concierge', 'Climatisation'],
    photos: [
      {
        id: 5,
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    userId: 'user-3',
    propertyType: 'Appartement',
    listingType: 'Location',
    title: 'T2 rénové avec balcon',
    description: 'Appartement refait à neuf dans immeuble récent',
    status: 'active',
    price: '1450',
    currency: 'EUR',
    address: '89 Boulevard de Courcelles',
    city: 'Paris',
    state: 'Île-de-France',
    country: 'France',
    postalCode: '75017',
    latitude: 48.8826,
    longitude: 2.3026,
    bedrooms: 2,
    bathrooms: 1,
    area: 55,
    amenities: ['Balcon', 'Ascenseur', 'Digicode', 'Cave'],
    photos: [
      {
        id: 6,
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    userId: 'user-4',
    propertyType: 'Maison',
    listingType: 'Vente',
    title: 'Maison de charme avec piscine',
    description: 'Belle maison bourgeoise dans quartier calme',
    status: 'active',
    price: '1850000',
    currency: 'EUR',
    address: '34 Avenue de la République',
    city: 'Saint-Cloud',
    state: 'Île-de-France',
    country: 'France',
    postalCode: '92210',
    latitude: 48.8442,
    longitude: 2.2089,
    bedrooms: 5,
    bathrooms: 4,
    area: 250,
    amenities: ['Piscine', 'Jardin', 'Garage 2 places', 'Cheminée', 'Sous-sol'],
    photos: [
      {
        id: 7,
        url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    userId: 'user-4',
    propertyType: 'Appartement',
    listingType: 'Location',
    title: 'Grand T3 avec vue Seine',
    description: 'Appartement spacieux avec vue dégagée',
    status: 'active',
    price: '1850',
    currency: 'EUR',
    address: '56 Quai de Grenelle',
    city: 'Paris',
    state: 'Île-de-France',
    country: 'France',
    postalCode: '75015',
    latitude: 48.8495,
    longitude: 2.2834,
    bedrooms: 3,
    bathrooms: 2,
    area: 85,
    amenities: ['Vue Seine', 'Balcon', 'Parking', 'Cave', 'Gardien'],
    photos: [
      {
        id: 8,
        url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
